//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Hart.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wpf_Hart.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Device Function Flags : .
        /// </summary>
        public static string R_Device_function {
            get {
                return ResourceManager.GetString("R_Device_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Device Type Code : .
        /// </summary>
        public static string R_Device_Type_Code {
            get {
                return ResourceManager.GetString("R_Device_Type_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardware Version : .
        /// </summary>
        public static string R_Hardware_version {
            get {
                return ResourceManager.GetString("R_Hardware_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Langue :.
        /// </summary>
        public static string R_langue {
            get {
                return ResourceManager.GetString("R_langue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manufacturer Code : .
        /// </summary>
        public static string R_Manufacturer_Code {
            get {
                return ResourceManager.GetString("R_Manufacturer_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Port spid :.
        /// </summary>
        public static string R_Port_spid {
            get {
                return ResourceManager.GetString("R_Port_spid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preambul Leng : .
        /// </summary>
        public static string R_Preambul_leng {
            get {
                return ResourceManager.GetString("R_Preambul_leng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read.
        /// </summary>
        public static string R_Read {
            get {
                return ResourceManager.GetString("R_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saive.
        /// </summary>
        public static string R_Saive {
            get {
                return ResourceManager.GetString("R_Saive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not Saive Changes.
        /// </summary>
        public static string R_Saive_dont {
            get {
                return ResourceManager.GetString("R_Saive_dont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Setings.
        /// </summary>
        public static string R_Setings {
            get {
                return ResourceManager.GetString("R_Setings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Software Version : .
        /// </summary>
        public static string R_Software_version {
            get {
                return ResourceManager.GetString("R_Software_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version of Specific Commands : .
        /// </summary>
        public static string R_Specific_commands {
            get {
                return ResourceManager.GetString("R_Specific_commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start Search Devices.
        /// </summary>
        public static string R_Start_Search_Devices {
            get {
                return ResourceManager.GetString("R_Start_Search_Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop.
        /// </summary>
        public static string R_Stop {
            get {
                return ResourceManager.GetString("R_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version of Universal Commands : .
        /// </summary>
        public static string R_Universal_commands {
            get {
                return ResourceManager.GetString("R_Universal_commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write.
        /// </summary>
        public static string R_Write {
            get {
                return ResourceManager.GetString("R_Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write_time :.
        /// </summary>
        public static string R_Write_time {
            get {
                return ResourceManager.GetString("R_Write_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write timeout :.
        /// </summary>
        public static string R_Write_timeout {
            get {
                return ResourceManager.GetString("R_Write_timeout", resourceCulture);
            }
        }
    }
}
